### ISSUE TITLE
Autoupdate build with a Github action

### ISSUE THREAD

**Issue by NotEternal** [noxonsu/dash.onout.org#22]
```
name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
...
```
